### ISSUE TITLE
I have a Tribe Called Quest-ion. 

### ISSUE THREAD

**Issue by t-scott** [adamxmiranda/Tupac_age#1]
I have concern that this tupac_age is too dope. I'm not sure how other packages will gain 8-tracktion with this package in the Ether. This package has the promise to be the Rolls Royce da 5'9 of packages. Please consider toning down how Nas-ty this package is.

**Comment by adamxmiranda** [comment]
I appreciate the concern, but I don't think the levels of dopeness will reach unsafe levels until I can figure out a rap pun for my ATAC-seq function

**Comment by t-scott** [comment]
Thank you for your correspondence. Best of luck with your ATACtion Bronson-seq.

**Comment by adamxmiranda** [comment]
Unsafe levels have been reached. Shouldn't have made a logo

**Comment by t-scott** [comment]
In the words of Big Matthew, "Dumb litty." Very impressed with the logo and Pun B's.
